### ISSUE TITLE
Cucumber test fail for supplyagreement template

### ISSUE THREAD

**Issue by irmerk** [accordproject/cicero-template-library#202]
Currently running `12 steps (1 failed, 11 passed)` on `supplyagreement`. When testing, there was an external `.js` file for state and another for request.

State:
```
{
   "$class": "org.accordproject.supplyagreement.AgreementState",
   "stateId": "org.accordproject.supplyagreement.AgreementState#1",
   "purchaseObligation" : null,
   "deliveryObligation" : null,
   "paymentObligation" : null
 }
```

Request:
```
{
   "$class": "org.accordproject.supplyagreement.ForecastRequest",
   "supplyForecast": 1200.0
}
```

When command is run `cicero execute -—request req1.js -—state state1.js`, this returns:
```
{
  "clause": "supplyagreement@0.8.1-1b83eed11769be2306c88e8cd56f4b89cfde8644f74db0a7d70ce0b044781a49",
  "request": {
    "$class": "org.accordproject.supplyagreement.ForecastRequest",
    "supplyForecast": 1200
  },
  "response": {
    "$class": "org.accordproject.supplyagreement.ForecastResponse",
    "transactionId": "f4b88cdb-ec55-41d1-bd55-6c6f1648d2ab",
    "timestamp": "2019-02-20T22:52:04.398Z"
  },
  "state": {
    "$class": "org.accordproject.supplyagreement.AgreementState",
    "purchaseObligation": {
      "$class": "org.accordproject.supplyagreement.PurchaseObligation",
      "requiredPurchase": 1020,
      "year": 2019,
      "quarter": 1,
      "party": "PETER"
    },
    "stateId": "org.accordproject.supplyagreement.AgreementState#1"
  },
  "emit": []
}
```

So, taking that state:
```
"$class": "org.accordproject.supplyagreement.AgreementState",
"purchaseObligation": {
  "$class": "org.accordproject.supplyagreement.PurchaseObligation",
  "requiredPurchase": 1020,
  "year": 2019,
  "quarter": 1,
  "party": "PETER"
},
"stateId": "org.accordproject.supplyagreement.AgreementState#1"
```
And listing it as the `Then the new state of the contract should be` result in the `logic.feature` file.

Still receiving this error message:
```
✖ Then the new state of the contract should be # ../../node_modules/@accordproject/cicero-engine/lib/steps.js:189
       """
       {
           "$class": "org.accordproject.supplyagreement.AgreementState",
           "purchaseObligation": {
             "$class": "org.accordproject.supplyagreement.PurchaseObligation",
             "requiredPurchase": 1020.0,
             "year": 2019,
             "quarter": 1,
             "party": "PETER"
           },
           "stateId": "org.accordproject.supplyagreement.AgreementState#1"
       }
       """
       {}
       Error
           at orgXaccordprojectXsupplyagreementXSupplyAgreement_demandforecast (vm.js:61:11)
           at __dispatch (vm.js:1218:17)
           at vm.js:1198:9
           at ContextifyScript.Script.runInContext (vm.js:59:29)
           at VM.run (/Users/jolenelanglinais/Code/Clause/CucumberWkShp/cicero-template-library/node_modules/vm2/lib/main.js:211:72)
           at Engine.execute (/Users/jolenelanglinais/Code/Clause/CucumberWkShp/cicero-template-library/node_modules/@accordproject/cicero-engine/lib/engine.js:233:27)
           at send (/Users/jolenelanglinais/Code/Clause/CucumberWkShp/cicero-template-library/node_modules/@accordproject/cicero-engine/lib/steps.js:53:19)
           at World.<anonymous> (/Users/jolenelanglinais/Code/Clause/CucumberWkShp/cicero-template-library/node_modules/@accordproject/cicero-engine/lib/steps.js:196:16)
```

**Comment by jeromesimeon** [comment]
This is due to a combination of:
1. the template manipulates time, and the tests should make sure the current time is set appropriately
2. if no time is set, the tests assume unix zero time is the current time, which makes the following enforce condition on the demand forecast fail. This corresponds to this line in the Ergo logic:
https://github.com/accordproject/cicero-template-library/blob/3871da87c710f75d942aeb33562b4af4f13d79f0/src/supplyagreement/lib/logic.ergo#L54
3. The error reporting for ergo logic errors in Cicero is really bad, I believe this might be a regression and an issue should be open on Cicero for that.

There is a proposed fix here https://github.com/jeromesimeon/cicero-template-library/commit/fb0c739b7932a71778830344b00090f04ae05eae

**Comment by raghavpatnecha** [comment]
@irmerk Can I take this issue

**Comment by jeromesimeon** [comment]
@irmerk Maybe this is closed?
